Ch09: Revision for the Handlebars Java with validation against the MVC 1.0 EDR does not work and Fix the hamcrest versus mockito versus junit matcher conflict See also: http://stackoverflow.com/questions/7869711/getting-nosuchmethoderror-org-hamcrest-matcher-describemismatch-when-running